table(X2023_STB_survey$Gender)
ECN <- table(X2023_STB_survey$Gender)
prop.table(ECN)
table(X2023_STB_survey$Gender,X2023_STB_survey$Grade)
barplot(table(X2023_STB_survey$Nationality))
barplot(table(X2023_STB_survey$`residential area`),xlab = "residential area",ylab = "residential area quantity",horiz = TRUE)
entry <- table(X2023_STB_survey$Gender, X2023_STB_survey$Grade)
barplot(entry, legend = TRUE)
pie(table(X2023_STB_survey$Grade))
hist(X2023_STB_survey$Age, main="age",col = terrain.colors(12),freq = FALSE)
lines(density(X2023_STB_survey$Age),lwd=2)
boxplot(X2023_STB_survey$Age~X2023_STB_survey$Grade,col = "purple",xlab = "grade",ylab = "age")
plot(x=X2023_STB_survey$Grade,y=X2023_STB_survey$Age,xlab = "Grade",ylab = "Age")